### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [searchy2/Rocket-Notes#1]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by rayliverified** [comment]
Hi Olay,

Thanks for offering to help! I've always felt that this app was missing a tutorial. 

How would you like to incorporate the FAQ into the app? I've made FAQs for other apps so I have a system in place but I'd like to hear your thoughts. 

This is very exciting, hope to hear back soon!

**Comment by olayhemy** [comment]
Thanks for response!

I will write the FAQs according to your request, let me know how you want it to be and what should be included to what I’m writing. Then, I will pull request for you to merge.

Thanks

**Comment by rayliverified** [comment]
Let me setup the structure/implementation for you. Then you can write whatever you feel is helpful, that's up to you!

**Comment by rayliverified** [comment]
Please check out the newly created faq branch. There, I've made a demo of how I do FAQs and Tutorials in my apps. You can find the FAQ in the settings screen (location not final). 

Essentially, I display the FAQ as a website page and load it using the webview. The website files are all optimized to run offline and ship with the app for fast loading times. 

The website files are located in the assets folder. 

Let me know what you think and if you have any questions!

**Comment by rayliverified** [comment]
One caveat is that offline loading of webpages does not work in API 16 and below so for those devices the webpage will be loaded remotely through a string override.

**Comment by rayliverified** [comment]
Any progress?

**Comment by rayliverified** [comment]
Closing due to no response.
